In [1]:
import pandas as pd
import numpy as np


In [2]:
arr =['p','r','s','q','t']
s1 =pd.Series(arr)
s1

0    p
1    r
2    s
3    q
4    t
dtype: object

In [3]:
type(s1)

pandas.core.series.Series

In [8]:
import numpy  as np
s1[0],s1[2]

('p', 's')

In [9]:
order =[1,5,3,3,4]
s2 =pd.Series(arr, index=order)
s2

1    p
5    r
3    s
3    q
4    t
dtype: object

s3=pd.Series(['pineapple','apple','orange','queen'], index=['p','q','r','s'])
s3


In [10]:
s3=pd.Series(['pineapple','apple','orange','queen'], index=['p','q','r','s']) 
s3

p    pineapple
q        apple
r       orange
s        queen
dtype: object

In [11]:
s3["p":"s"]

p    pineapple
q        apple
r       orange
s        queen
dtype: object

In [12]:
s3[0:3]

p    pineapple
q        apple
r       orange
dtype: object

In [13]:
s3.index


Index(['p', 'q', 'r', 's'], dtype='object')

In [16]:
s3[s3=='apple'].index[0]

'q'

In [15]:
s3=='apple'

p    False
q     True
r    False
s    False
dtype: bool

In [19]:
d={'a':1,'b':2,'c':3,'d':4,'e':5}
s3=pd.Series(d)
s3

a    1
b    2
c    3
d    4
e    5
dtype: int64

s4=s1.append(s2)
s4

In [24]:
s4=s1.append(s2)

s4

C:\Users\gtu\AppData\Local\Temp\ipykernel_6344\1859497992.py:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  s4=s1.append(s2)


0    p
1    r
2    s
3    q
4    t
1    p
5    r
3    s
3    q
4    t
dtype: object

In [25]:
import numpy as np

s4.index=np.arrange(10)
s4

AttributeError: module 'numpy' has no attribute 'arrange'

In [27]:
ser1=(['100','20','10','150','60'],['India','Pakistan','Nepal','China','Germany'])
ser2=(['20','100','30','10','15'],['India','Pakistan','Japan','China','Korea'])

In [28]:
ser1+ser2

(['100', '20', '10', '150', '60'],
 ['India', 'Pakistan', 'Nepal', 'China', 'Germany'],
 ['20', '100', '30', '10', '15'],
 ['India', 'Pakistan', 'Japan', 'China', 'Korea'])

In [29]:
ser1

(['100', '20', '10', '150', '60'],
 ['India', 'Pakistan', 'Nepal', 'China', 'Germany'])

ser2

In [35]:
ser2


(['20', '100', '30', '10', '15'],
 ['India', 'Pakistan', 'Japan', 'China', 'Korea'])

In [36]:
print("Median",s6.median())
print("Max",s6.max())
print("Std",s6.std())

NameError: name 's6' is not defined

In [31]:
import numpy as np
arr=np.random.randn(6,4)
arr

array([[ 1.26099695e+00, -2.18724379e-01,  9.40920048e-04,
        -3.01283092e-01],
       [ 9.77180314e-01, -9.83969345e-01,  4.74582320e-01,
         2.28250083e-01],
       [-1.64131541e-01,  1.33113775e+00, -7.10706571e-01,
         2.13336717e+00],
       [-4.47444227e-01, -1.18708583e+00,  5.16907562e-01,
         8.27053480e-01],
       [-9.91645712e-01,  6.41330943e-01,  2.08173405e-01,
        -7.63737447e-01],
       [-1.20356643e-01, -1.02576088e+00,  7.29473472e-01,
        -5.39603577e-01]])

In [32]:
arr1=np.random.randint(24,size=(6,4))
arr1

array([[23, 22, 11,  4],
       [ 6, 14,  6, 14],
       [16,  1, 19, 14],
       [ 3, 19, 22, 11],
       [ 0,  2, 12, 21],
       [20,  1, 17, 14]])

In [34]:
row=["A","B","C","D","E","F"]
column=['1','2','3','4']
df=pd.DataFrame(arr1,index=row,columns=column)
df

1   2   3   4
A  23  22  11   4
B   6  14   6  14
C  16   1  19  14
D   3  19  22  11
E   0   2  12  21
F  20   1  17  14

In [37]:
df.head(3)

1   2   3   4
A  23  22  11   4
B   6  14   6  14
C  16   1  19  14

In [38]:
df.describe(include='all')

1          2          3         4
count   6.000000   6.000000   6.000000   6.00000
mean   11.333333   9.833333  14.500000  13.00000
std     9.584710   9.662643   5.890671   5.51362
min     0.000000   1.000000   6.000000   4.00000
25%     3.750000   1.250000  11.250000  11.75000
50%    11.000000   8.000000  14.500000  14.00000
75%    19.000000  17.750000  18.500000  14.00000
max    23.000000  22.000000  22.000000  21.00000

In [40]:
df=pd.DataFrame(arr1)
df

0   1   2   3
0  23  22  11   4
1   6  14   6  14
2  16   1  19  14
3   3  19  22  11
4   0   2  12  21
5  20   1  17  14

In [41]:
row=["A","B","C","D","E","F"]
column=['1','2','3','4']
df=pd.DataFrame(arr1)
df

0   1   2   3
0  23  22  11   4
1   6  14   6  14
2  16   1  19  14
3   3  19  22  11
4   0   2  12  21
5  20   1  17  14

In [45]:
df.describe()

0          1          2         3
count   6.000000   6.000000   6.000000   6.00000
mean   11.333333   9.833333  14.500000  13.00000
std     9.584710   9.662643   5.890671   5.51362
min     0.000000   1.000000   6.000000   4.00000
25%     3.750000   1.250000  11.250000  11.75000
50%    11.000000   8.000000  14.500000  14.00000
75%    19.000000  17.750000  18.500000  14.00000
max    23.000000  22.000000  22.000000  21.00000

In [42]:
summ=df.describe(include='all')

In [43]:
summ

0          1          2         3
count   6.000000   6.000000   6.000000   6.00000
mean   11.333333   9.833333  14.500000  13.00000
std     9.584710   9.662643   5.890671   5.51362
min     0.000000   1.000000   6.000000   4.00000
25%     3.750000   1.250000  11.250000  11.75000
50%    11.000000   8.000000  14.500000  14.00000
75%    19.000000  17.750000  18.500000  14.00000
max    23.000000  22.000000  22.000000  21.00000

In [44]:
df.tail(2)

0  1   2   3
4   0  2  12  21
5  20  1  17  14

In [46]:
type(summ)

pandas.core.frame.DataFrame

In [50]:
df.isnull().sum().sum()

0

In [51]:
df.isnull().any()

0    False
1    False
2    False
3    False
dtype: bool

In [52]:
df.isnull().all()

0    False
1    False
2    False
3    False
dtype: bool

In [53]:
import pandas as pd
studentData = {
    'name' : ['jack', 'Riti', 'Aadi','Bhavna'],
    'age' : ["?", 30, "?",32],
    'salary':[10000,150298,75000,200000],
    'city' : ['Sydney',"Delhi", 'New york','Maryland']

}
rowlabel=['A','B','C','D']

In [54]:
df1=pd.DataFrame(studentData,index=rowlabel)
df1

name age  salary      city
A    jack   ?   10000    Sydney
B    Riti  30  150298     Delhi
C    Aadi   ?   75000  New york
D  Bhavna  32  200000  Maryland

In [55]:
df1.isnull().sum()

name      0
age       0
salary    0
city      0
dtype: int64

In [56]:
df1.dtypes

name      object
age       object
salary     int64
city      object
dtype: object

In [57]:
df1.index


Index(['A', 'B', 'C', 'D'], dtype='object')

In [58]:
df1.info

<bound method DataFrame.info of      name age  salary      city
A    jack   ?   10000    Sydney
B    Riti  30  150298     Delhi
C    Aadi   ?   75000  New york
D  Bhavna  32  200000  Maryland>

In [59]:
df1.columns

Index(['name', 'age', 'salary', 'city'], dtype='object')

In [60]:
df1.values

array([['jack', '?', 10000, 'Sydney'],
       ['Riti', 30, 150298, 'Delhi'],
       ['Aadi', '?', 75000, 'New york'],
       ['Bhavna', 32, 200000, 'Maryland']], dtype=object)

In [61]:
df1['age']=='?'

A     True
B    False
C     True
D    False
Name: age, dtype: bool

In [62]:
df1['age'].unique()

array(['?', 30, 32], dtype=object)

In [63]:
df1.loc[df1['age']=='?']

name age  salary      city
A  jack   ?   10000    Sydney
C  Aadi   ?   75000  New york

In [64]:
df2=df1.loc[df1['age']!='?']
df2

name age  salary      city
B    Riti  30  150298     Delhi
D  Bhavna  32  200000  Maryland

In [1]:
# import the pandas library
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(5, 3), index=['a', 'c', 'e', 'f',
'h'])
print (df)

          0         1         2
a -1.507464  0.793588 -0.623731
c  0.259171 -0.408355 -0.348840
e -0.092041 -0.960087 -0.244027
f  0.340292 -0.258187  0.211809
h -0.309360 -0.418427  0.930339


In [2]:
df.columns=['one', 'two', 'three']
df

one       two     three
a -1.507464  0.793588 -0.623731
c  0.259171 -0.408355 -0.348840
e -0.092041 -0.960087 -0.244027
f  0.340292 -0.258187  0.211809
h -0.309360 -0.418427  0.930339

In [3]:
df = df.reindex(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])
df

one       two     three
a -1.507464  0.793588 -0.623731
b       NaN       NaN       NaN
c  0.259171 -0.408355 -0.348840
d       NaN       NaN       NaN
e -0.092041 -0.960087 -0.244027
f  0.340292 -0.258187  0.211809
g       NaN       NaN       NaN
h -0.309360 -0.418427  0.930339

In [4]:
print(df.head())

        one       two     three
a -1.507464  0.793588 -0.623731
b       NaN       NaN       NaN
c  0.259171 -0.408355 -0.348840
d       NaN       NaN       NaN
e -0.092041 -0.960087 -0.244027


In [7]:
df.isnull()

one    two  three
a  False  False  False
b  False   True   True
c  False  False  False
d  False   True   True
e  False  False  False
f  False  False  False
g  False   True   True
h  False  False  False

In [8]:
df.isnull().sum()

one      0
two      3
three    3
dtype: int64

In [9]:
df[df.columns[df.isnull().any()]]

two     three
a  0.793588 -0.623731
b       NaN       NaN
c -0.408355 -0.348840
d       NaN       NaN
e -0.960087 -0.244027
f -0.258187  0.211809
g       NaN       NaN
h -0.418427  0.930339

In [10]:
da=df.columns[df.isnull().any()]
da

Index(['two', 'three'], dtype='object')

In [11]:
df['one'].fillna(df['one'].mean(),inplace=True)

In [12]:
df

one       two     three
a -1.507464  0.793588 -0.623731
b -0.261880       NaN       NaN
c  0.259171 -0.408355 -0.348840
d -0.261880       NaN       NaN
e -0.092041 -0.960087 -0.244027
f  0.340292 -0.258187  0.211809
g -0.261880       NaN       NaN
h -0.309360 -0.418427  0.930339

In [13]:
df['two'].fillna(method='bfill',inplace=True)

In [14]:
df


one       two     three
a -1.507464  0.793588 -0.623731
b -0.261880 -0.408355       NaN
c  0.259171 -0.408355 -0.348840
d -0.261880 -0.960087       NaN
e -0.092041 -0.960087 -0.244027
f  0.340292 -0.258187  0.211809
g -0.261880 -0.418427       NaN
h -0.309360 -0.418427  0.930339

In [15]:
df['one'].unique()

array([-1.50746405, -0.26188035,  0.25917102, -0.09204096,  0.34029193,
       -0.3093597 ])

In [17]:
df.fillna(df['two'].mean(),inplace=True)

In [18]:
df

one       two     three
a -1.507464  0.793588 -0.623731
b -0.261880 -0.408355 -0.379792
c  0.259171 -0.408355 -0.348840
d -0.261880 -0.960087 -0.379792
e -0.092041 -0.960087 -0.244027
f  0.340292 -0.258187  0.211809
g -0.261880 -0.418427 -0.379792
h -0.309360 -0.418427  0.930339