# 1.Write a Python program to swap first and last element of the list.

In [1]:
def swapList(list):
     
    # Storing the first and last element
    get = list[-1], list[0]
     
    # unpacking those elements
    list[0], list[-1] = get
     
    return list

In [2]:
newList = [12, 35, 9, 56, 24]
print(swapList(newList))

[24, 35, 9, 56, 12]


# 2.Write Python program to find the length of list using for loop.

In [3]:
test_list = [1, 4, 5, 7, 8]

In [4]:
print("The list is : " + str(test_list))

The list is : [1, 4, 5, 7, 8]


In [5]:
counter = 0
for i in test_list:
    counter = counter + 1
print("Length of list is : " + str(counter))

Length of list is : 5


# 3. Given a list of numbers, you need to write a Python program to find the second largest number in the list.

In [6]:
list1 =[10,56,23,89,23,45,90,110,34,78]

In [7]:
list2 = list(set(list1))

In [8]:
list2.sort()

In [9]:
print("Second largest element is:", list2[-2])

Second largest element is: 90


# 4. Write a program to perform addition, subtraction, multiplication, integer division, floor division and modulo division on two integer and float.

In [10]:
var1=10
var2=30
sum=var1+var2
print("The sum of",var1,"and",var2,"is:",sum)

The sum of 10 and 30 is: 40


In [11]:
var1=50
var2=30
diff=var1-var2
print("The difference between",var1,"and",var2,"is:",diff)

The difference between 50 and 30 is: 20


In [12]:
var1=50
var2=30
product=var1*var2
print("The product of",var1,"and",var2,"is:",product)

The product of 50 and 30 is: 1500


In [13]:
var1=50
var2=30
quotient=var1/var2
print("The quotient of",var1,"and",var2,"is:",quotient)

The quotient of 50 and 30 is: 1.6666666666666667


In [14]:
var1=50
var2=30
rem=var1%var2
print("The remainder of",var1,"and",var2,"is:",rem)

The remainder of 50 and 30 is: 20


In [15]:
var1=10
var2=7
floordiv=var1//var2
print("The floor division between",var1,"and",var2,"is:",floordiv)

The floor division between 10 and 7 is: 1


# 5.Write a program to convert degree Fahrenheit to Celsius

In [16]:
celsius = 54
fahrenheit = (celsius * 1.8) + 32
print(str(celsius )+ " degree Celsius is equal to " + str(fahrenheit )+ " degree Fahrenheit.")

54 degree Celsius is equal to 129.2 degree Fahrenheit.


# 6.Write a python program to find whether given string is palindrome

In [17]:
def isPalindrome(s):
    return s == s[::-1]

In [18]:
s = "amaama"
ans = isPalindrome(s)
  
if ans:
    print("Yes")
else:
    print("No")

Yes


# 7. Write a python program using for loop to get the sum of given tuple

In [39]:
test_tup = (13,56,78,23,67,89,23)
 
# printing original tuple
print("The original tuple is : " + str(test_tup))

The original tuple is : (13, 56, 78, 23, 67, 89, 23)


In [40]:
res = 0
for i in test_tup:
    res += i

In [41]:
print("The summation of tuple elements are : " + str(res))

The summation of tuple elements are : 349


# 8. Write a python program to find the sum of dictionary values

In [42]:
def returnSum(dict):
 
    sum = 0
    for i in dict.values():
        sum = sum + i
 
    return sum

In [43]:
dict = {'a': 100, 'b': 200, 'c': 300}
print("Sum :", returnSum(dict))

Sum : 600


# 9. Write a python program using inline function lambda to find the sum of list

In [44]:
def add(data):
    s=0
    for n in data:
        s=s+n
    return s

In [45]:
fiboList = [0,1,1,2,3,5,8,13,21,34,55]
print("List of fibonacci numbers :",fiboList)

List of fibonacci numbers : [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55]


In [46]:
listSum = add(fiboList)
print("The sum of all elements is ",listSum)

The sum of all elements is  143


# 10. Write a python program to multiply an Identity matrix of dimension 3-by-3 with given matrix

In [57]:
A=([[9,10,11],
[12,13,14],
[15,16,17]])

B=([[9,10,11],
[12,13,14],
[15,16,17]])



In [58]:
print(np.dot(A,B))
 

NameError: name 'np' is not defined

# 11. Write a program to Check whether a NumPy array contains a specified row

In [60]:
import numpy as np

In [63]:
num = np.arange(20)
arr1 = np.reshape(num, [4, 5])

In [64]:
print("Original array:")
print(arr1)
print([0, 1, 2, 3, 4] in arr1.tolist())
print([0, 1, 2, 3, 5] in arr1.tolist())
print([15, 16, 17, 18, 19] in arr1.tolist())

Original array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
True
False
True


# 12. Write a python program to flatten the NumPy matrix of size 3-by-3

In [68]:
import numpy as np
y = np.array([[[2,3,4],[7,8,9], [4,5,6]]])
y.flatten()

array([2, 3, 4, 7, 8, 9, 4, 5, 6])